gh-blue-barracudas/grace-shopper

- server/db/models/cart.js
- server/db/models/cart.spec.js
- server/db/models/index.js
> Finished writing cart model

- README.md
- server/db/models/user.js
> User model

- server/db/models/index.js
- server/db/models/products.js
> product model

- server/db/models/index.js
> user-cart associations

- package-lock.json
- server/api/index.js
- server/api/products.js
> route for all products

- script/seed.js
> Finished seed file

- client/store/index.js
- client/store/product.js
- package-lock.json
- package.json
- server/api/products.js
- server/db/models/products.js
> database: graceshopper

- .prettierignore
- script/seed.js
- server/api/products.js
---
fixes #38, #55, update the seed file
> seed file product imagesUrl

- client/components/all-products.js
- client/components/home.js
- client/components/index.js
- client/routes.js
- client/store/index.js
- client/store/product.js
> all products rendering

- client/components/all-products.js
- client/routes.js
- public/style.css
- script/seed.js
> feat react renders all products category page

- client/components/all-products.js
- client/components/index.js
- client/components/single-product.js
- client/store/product.js
> [feat] react - adds single component

- client/components/all-products.js
- public/style.css
> flex wrap items

- client/app.js
- client/components/cart.js
- client/components/home.js
- client/components/index.js
- client/components/navbar.js
- client/components/single-product.js
- client/routes.js
- client/store/cart.js
- public/index.html
- public/style.css
> Cart component

- client/components/cart.js
- client/components/single-product.js
- client/store/cart.js
- public/style.css
> feat(cart) add cart button working

- client/components/cart.js
- server/api/cart.js
> set up route to get all products in cart

- client/components/cart.js
- client/components/emptycart.js
- client/components/index.js
- client/components/navbar.js
- client/routes.js
- client/store/cart.js
- server/api/cart.js
> feat(cart) bugfix about cart routes

- client/components/cart.js
- client/store/cart.js
- server/api/cart.js
> [feat] express react - adds full cart functionality

- client/components/cart.js
- client/store/cart.js
> feat(redux cart) Cart displays products, updates quantities and total

- client/components/cart.js
- client/components/emptycart.js
- public/style.css
> feat(cart) cart works with all its functionalities

- client/app.js
- client/components/aboutUs.js
- client/components/all-products.js
- client/components/footer.js
- client/components/home.js
- client/components/single-product.js
- public/style.css
> [fix] css - fixes footer placement, hpg buttons, adds prd graphic

- client/components/home.js
- client/components/navbar.js
- client/components/notFound.js
- client/components/orderConfirm.js
- client/components/single-product.js
- public/style.css
- script/seed.js
> [feat]html css - adds cloud hover on hpg and single page

- .travis.yml
- README.md
- package.json
> [misc] updates ReadMe to be about the grace shopper project

- client/components/checkout.js
- client/components/index.js
- client/components/order-history.js
- client/components/user-home.js
- client/routes.js
- client/store/user.js
- package-lock.json
- public/style.css
- server/api/users.js
- server/db/models/user.js
---
fixes #93 fixes #41 fixes #102
> [feat] user route to update address info and updates checkout form

- client/components/checkout.js
> [fix] react changes zip from 0 to empty string

- README.md
- public/style.css
- server/api/cart.js
> [fix] CSS fixes CSS issue for the user account page

- .travis.yml
> [fix] changes create database script in travis.yml

- .gitignore
- client/components/user-home.js
- server/auth/google.js
- server/db/models/user.js
> [feat] adds google oauth

- client/components/footer.js
- public/index.html
- public/style.css
> [fixes] html css - fixes hpg text and takes off mailto on footer

- client/components/user-home.js
- client/store/user.js
- public/index.html
- server/api/users.js
…ame, last name, and email
---
fixes #109
> [feat] react, redux, express - Adds ability for user to edit first name, last name, and email

- client/components/checkout.js
- client/components/checkoutOriginal.js
- package-lock.json
- package.json
- server/api/users.js
- server/index.js
> feat(stripePayment) functioning with dummy data

- client/store/index.js
- package-lock.json
> [fix] Removes redux log from the production environment

- server/api/cart.js
- server/authCheckMiddle.js
> adds middleware to all cart  routes - test

- server/authCheckMiddle.js
> [fix]express - adds security to param routes

- client/components/checkout.js
- server/api/users.js
> [feat](stripe checkout) real data

- client/components/aboutUs.js
- client/components/cart.js
- client/components/checkout.js
- client/components/footer.js
- client/components/user-home.js
- public/index.html
- public/style.css
---
fixes #68, fixes #128, fixes #40, fixes #108
> [fix]css - adds margin borders, updates footer
